/*
 * Automatically generated by Magic.
 */
CREATE TABLE requests(
  request_id integer not null primary key autoincrement,
  prompt text not null,
  code_file text not null,
  is_error integer not null default 0
);

