/*
 * Automatically generated by Magic.
 */
CREATE TABLE requests(
  request_id integer not null primary key autoincrement,
  is_error integer not null default 0,
  result_file text, 
  prompt text not null,
  execution_count
  integer not null default 1
);

